pgx/src/pgx.ml
pgx_test/src/pgx_test.ml

There were two bugs here:
- COPY was adding an extra [] to the end of the result set
- simple_query was reversing the order of output rows
This fixes both by making COPY use the same code as other
result sets, and adding a reverse there.

Fix simple_query row order and COPY number of results

---

pgx.opam

This was missing but worked because of transitive dependencies.
Note: This is the lowest version we've tested, not the highest,
since we want to make the dependency as broad as possible.
As soon as beta17 comes out we'll need to bump our minimum
version though (for inline test support).

Add jbuilder build dependency

---

.circleci/config.yml
pgx/src/jbuild
pgx_async.opam
pgx_async/bin/pgx_async_example.ml
pgx_async/src/jbuild
pgx_async/src/pgx_async.ml
pgx_lwt/src/jbuild
pgx_unix/src/jbuild

Remove runner directive - this causes an error (``) with the latest `ppx_driver`. Unclear of the reason why, but removing the driver directive fixes the issue.
Async API changes
* `String.create` deprecated, now `Bytes.create`
Safe-string changes
* In preparation for 4.06, turn on safe string & make changes necessary to comply

Support Async v0.10.0

---

pgx.opam
pgx/src/jbuild
pgx/test/jbuild
pgx_async/bin/jbuild
pgx_async/test/jbuild
pgx_lwt/test/jbuild
pgx_test/src/jbuild
pgx_unix/test/jbuild

Somehow this was implicit before Core v0.11 but it needs to be
explicit now. Long-term we might want to see how hard it is to
remove this, since we don't really do much with sexps.

Add explicit sexplib dependency to pgx

---

pgx.opam
pgx_async.opam
pgx_lwt.opam
pgx_unix.opam

Updated the .opam files so the packages can be installed with opam.
When using Jbuilder, [the `install` and `remove` directives are no longer
necessary](http://jbuilder.readthedocs.io/en/latest/usage.html#invocation-from-opam).

Update .opam files: make it installable with opam

---

Makefile
pgx_async/src/pgx_async_test.ml
pgx_test/src/pgx_test.ml

Output looks like this now:
```
$ make test
test_pgx_async_conversions alias pgx_async/test/runtest
...
Ran: 3 tests in: 0.13 seconds.
OK
test_pgx_value alias pgx/test/runtest
.........................................................................................................................Not_found
Not_found
..Not_found
....................
Ran: 143 tests in: 0.22 seconds.
OK
test_pgx_lwt alias pgx_lwt/test/runtest
..............................
Ran: 30 tests in: 0.01 seconds.
OK
test_pgx_async alias pgx_async/test/runtest
..............................
Ran: 30 tests in: 0.11 seconds.
OK
test_pgx_unix alias pgx_unix/test/runtest
..............................
Ran: 30 tests in: 0.12 seconds.
OK
```
I'm not sure why the Pgx.Value tests are printing those weird `Not_found`'s. We don't …

Quieter tests

---

pgx.descr
pgx_async.descr
pgx_lwt.descr
pgx_unix.descr

The name of the library shows up right next to the description in opam,
so we don't need to repeat it.
See the bottom of: https://opam.ocaml.org/packages/pgx/

Remove prefixes from .descr files

---

.circleci/config.yml

We previously had to manually list every .opam file, but this version
just pins and installs deps for every file present.
This mostly makes it easier to copy the Pgx config to new projects.

Make CircleCI pin all .opam files

---

Makefile
pgx/src/pgx.ml
pgx/src/pgx_value.ml
pgx_async/src/pgx_async.ml
pgx_async/src/pgx_async_test.mli
pgx_lwt/src/pgx_lwt.ml
pgx_unix/src/pgx_unix.ml

This turns on more warnings and makes warnings errors.
Notably, had to:
- Remove unused functions and imports
- Add a `; _` case when destructuring records

Compile in dev mode

---

pgx_async/src/pgx_async.ml

Debug messages should be printed with Log.Global.debug, not
logging directly to stderr.

Make pgx_async use Async.Log

---

pgx/src/pgx.ml

An excessively-long running process could theoretically use all 2^32
possible prepared statement names when using an int (32-bit), so
use a 64-bit int to guarantee that we'll never run out.

Change prepared statement auto-numbering to int64

---

pgx.opam
pgx/src/jbuild
pgx/src/pgx.ml
pgx/src/pgx_value.ml
pgx/test/test_pgx_value.ml

This should reduce the amount of dependencies needed for Pgx_unix
and Pgx_lwt

Use Sexplib0 instead of Sexplib

---

pgx/src/pgx.ml

This reverts commit 0f3174d9513702033d9479812e6b807ba0956e12.
This commit wasn't async thread safe, since we could have two
async threads prepare the unnamed statement before the first
thread was able to execute it.

Revert "Used the unnamed prepared statement for Pgx.execute"

---

README.md
pgx_async/bin/pgx_async_example.ml

This focuses on the parts of the interface that people should actually use,
and has a somewhat-reasonable organization for the code.
Also made some notes about how to apply that example to Pgx_lwt and Pgx_unix.

Replace the Pgx_async example with a better one

---

pgx_lwt/src/pgx_lwt.ml
pgx_unix/src/pgx_unix.ml

Before, I get a lot of:
```
Error: pgx_async:20:should fail without sequencer.
File
"/home/gary/dev/arena/godzilla/_build/default/pgx/pgx_lwt/test/oUnit-pgx_async-gary-macbook#01.log",
line 68, characters 1-1: Error: pgx_async:20:should fail without
sequencer (in the log).
Raised at file "pgx/pgx_test/src/pgx_test.ml", line 116, characters
20-31 Called from file "src/oUnitRunner.ml", line 46, characters 13-26
Unix.Unix_error(Unix.ENXIO, "getlogin", "")
```
After, it works

Work around getlogin failing for lwt

---

pgx/src/pgx_value.ml

Changed calls from `Re.get` to `Re.Group.get` to avoid deprecation
warnings.

Fix Re.get deprecation warnings

---

pgx.opam
pgx_test/src/pgx_test.ml

In opam 2.0, {test} should be {with-test}
We need base64 < 3.0, because the latest version is incompatible
with core-extended:
https://discuss.ocaml.org/t/what-to-do-about-files-both-define-module-base64/3426
This effectively reverts commit 03249c5a11b9572a10869ea2b427ae057be689b2

Fix with-test annotations and require base64 < 3.0.0

---

.circleci/config.yml
Makefile
pgx.opam

Instead of installing a separate dependency that's marked as deprecated by the author, use the native support of bisect_ppx to generate the coveralls report.

Use bisect_ppx native coveralls support

---

pgx.opam
pgx/src/dune
pgx/src/pgx.mli
pgx/src/pgx_aux.ml
pgx/src/pgx_value.ml
pgx/src/pgx_value_intf.ml
pgx/src/result_desc.mli
pgx/src/types.ml
pgx/test/dune
pgx/test/test_pgx_value.ml
pgx_unix/src/pgx_unix.ml

This is cherry-picking two commits from #57 so we can merge them before we're ready for the base64 change.

Mirage readiness

---

dune-project
pgx_unix.opam
pgx_value_core.opam

We need this since you can theoretically do:
```
opam install pgx
opam install -t pgx_value_core # fails because alcotest isn't installed
```

Duplicate test deps for each project

---

dune-project
pgx.opam
pgx_async.opam
pgx_lwt.opam
pgx_lwt_unix.opam
pgx_unix.opam

- Pgx_async, Pgx_unix, and Pgx_lwt need base64
- Pgx doesn't actually use base64
- Pgx_lwt doesn't have tests

Add base64 to with-tests

---

.circleci/config.yml
Makefile

- Add dune-release lint
- Build with -p
- Build before installing test deps

CI improvements

---

.circleci/config.yml
Makefile
dune-project
pgx_lwt_mirage.opam
pgx_lwt_mirage/src/dune
pgx_lwt_mirage/src/pgx_lwt_mirage.ml
pgx_lwt_mirage/src/pgx_lwt_mirage.mli
unikernel/config.ml
unikernel/unikernel.ml

to be released in https://github.com/ocaml/opam-repository/pull/16425

adapt to API changes of mirage-conduit (dns resolver now has a timeout)

---

pgx/src/dune
pgx/test/test_error_response.ml
pgx/test/test_pgx_value.ml
pgx_test/src/pgx_test.ml
pgx_value_core/src/pgx_value_core.mli

This makes us only expose the Pgx module at top-level.
Most of this stuff was never intended to be used directly, so the only
major change is that Pgx_value now _must_ be referenced as Pgx.Value.
Fixes #101

Set Pgx module to wrapped

---

.circleci/config.yml
dune-project
pgx/src/pgx.ml
pgx_lwt_mirage.opam

During the startup message flow postgres will shutdown the socket immediately after sending an error frame. Trying to read further from the socket will always result in EOF. If we instead exit early by raising the exception with  Error_response, the error message seen by pgx users will be a little better. For a login failure, before this PR we would see something like:
```
(monitor.ml.Error (Pgx_async.Pgx_eof)
("Raised at Pgx_async.Thread.input_char.(fun) in file \"pgx_async/src/pgx_async.ml\", line 50, characters 14-27"
"Called from Async_kernel__Deferred1.M.map.(fun) in file \"src/deferred1.ml\", line 17, characters 40-45"
"Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 167, characters 6-47"))
```
With the diff in this PR the error will show up as:
``` …
```

improve message for authentication errors

---

pgx_async/test/test_pgx_async.ml
pgx_lwt_unix/test/test_pgx_lwt.ml
pgx_test/src/pgx_test.ml
pgx_test/src/pgx_test.mli
pgx_unix/test/test_pgx_unix.ml

This makes it so the tests don't all claim to be pgx_async and instead show the correct library name.

Print the correct library name in tests

---

dune-project
pgx.opam
pgx_async.opam
pgx_lwt.opam
pgx_lwt_mirage.opam
pgx_lwt_unix.opam
pgx_unix.opam
pgx_value_core.opam

These are fixes found by the opam release process in https://github.com/ocaml/opam-repository/pull/18675
- Make our license field SPDX compatible
- Require conduit and re versions >= 1.5.0 since we're using Re.group and Conduit_async.V3
- Remove an unnecessary dep in pgx-lwt

Opam file fixes

---

dune-project
pgx_lwt_mirage.opam
pgx_lwt_mirage/src/dune
pgx_lwt_mirage/src/pgx_lwt_mirage.ml
pgx_lwt_mirage/src/pgx_lwt_mirage.mli
unikernel/config.ml
unikernel/unikernel.ml

This makes `pgx_lwt_mirage` build with modern Mirage dependencies.  It builds on #116 .

Update Mirage dependencies

---

.gitignore
pgx/src/pgx.ml

SASL is currently unsupported but has become the default in common postgres 14 setups. Instead of a hang, we can throw a real error until it can be supported.

Dont hang on SASL logins

---

dune-project
pgx.opam
pgx/src/dune

OCaml 5.0 removed `Stream` from the standard library and moved it to a separate `camlp-streams` package.

Add support for OCaml 5.0
